model_path: /home/wlsdzyzl/project/pyramid-3dunet/experiments/3d_asoca/UNET-STAGE2/FOLD1/last_checkpoint.pytorch
# model configuration
model:
  # model class
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (gcr - GroupNorm+Conv3d+ReLU)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of f_map levels
  num_levels: 3
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
  # if True applies the final normalization layer (sigmoid or softmax), otherwise the networks returns the output from the final convolution layer; use False for regression problems, e.g. de-noising
  is_segmentation: true
# predictor configuration
predictor:
  # standard in memory predictor
  name: 'StandardNIIPredictor'
  squeeze_if_one_channel: true
# specify the test datasets
loaders:
  dataset: CoarseSegmentedNIIDataset
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 64
  # mirror pad the raw data in each axis for sharper prediction near the boundaries of the volume
  # mirror_padding: [16, 32, 32]
  # path to the raw data within the NII
  raw_dir: raw
  label_dir: label
  # path to the the label data withtin the NII
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  output_dir: /home/wlsdzyzl/project/pyramid-3dunet/generated_files/predictions/3d_asoca/UNET-STAGE2
  test:
    # paths to the test datasets; if a given path is a directory all NII files
    # inside this this directory will be included as well (non-recursively)
    file_paths:
      - /media/wlsdzyzl/DATA1/datasets/ASOCA/nii/cropped_middle/fold1
    mask_path: /home/wlsdzyzl/project/pyramid-3dunet/generated_files/mask/3d_asoca/fold1/train
    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: MaskedSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [32, 32, 32]
      # stride between patches
      stride_shape: [24, 24, 24]
      # minimum volume of the labels in the patch
      threshold: 0.0
      # probability of accepting patches which do not fulfil the threshold criterion
      slack_acceptance: 0.01

    transformer:
        raw:
          - name: Standardize
          - name: ToTensor
            expand_dims: true