# Trained on data from the 2018 Kaggle Data Science Bowl: https://www.kaggle.com/c/data-science-bowl-2018/data
manual_seed: 2023
model:
  name: UNet3D
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: 32
  # number of f_map levels
  num_levels: 3
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
  is_segmentation: true
regularizer:
  name: none
trainer:
  checkpoint_dir: /home/wlsdzyzl/project/pyramid-3dunet/experiments/3d_asoca/UNET-STAGE2/test
  resume: /home/wlsdzyzl/project/pyramid-3dunet/experiments/3d_asoca/UNET-STAGE2/FOLD1/last_checkpoint.pytorch
  pre_trained: null
  validate_after_iters: 80
  log_after_iters: 40
  max_num_epochs: 40
  max_num_iterations: 15000000
  eval_score_higher_is_better: True
optimizer:
  # initial learning rate
  learning_rate: 0.01
  # weight decay
  weight_decay: 0.00001
loss:
  name: BCEDiceLoss
  # a target value that is ignored and does not contribute to the input gradient
  ignore_index: null
  # skip the last channel in the target (i.e. when last channel contains data not relevant for the loss)
  skip_last_target: false
eval_metric:
  name: MeanIoU
  threshold: 0.5
lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.5
  patience: 30

# Configure training and validation loaders
loaders:
  dataset: CoarseSegmentedNIIDataset
  # how many subprocesses to use for data loading
  num_workers: 8
  batch_size: 64
  # path to the raw data within the H5
  raw_dir: raw
  # path to the the label data withtin the H5
  label_dir: label
  mask_path: 
  # configuration of the train loader
  # skeleton_dir: skeleton
  truncation: [-400, 400]
  train:
    # path to the training datasets
    file_paths:
      - /media/wlsdzyzl/DATA1/datasets/ASOCA/nii/cropped_middle/fold2
      - /media/wlsdzyzl/DATA1/datasets/ASOCA/nii/cropped_middle/fold3
      - /media/wlsdzyzl/DATA1/datasets/ASOCA/nii/cropped_middle/fold4
      - /media/wlsdzyzl/DATA1/datasets/ASOCA/nii/cropped_middle/fold5  
    mask_path: /home/wlsdzyzl/project/pyramid-3dunet/generated_files/mask/3d_asoca/fold1/train
    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: MaskedSliceBuilder
      # train patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [32, 32, 32]
      # stride between patches
      stride_shape: [24, 24, 24]
      # minimum volume of the labels in the patch
      threshold: 0.0
      # probability of accepting patches which do not fulfil the threshold criterion
      slack_acceptance: 0.01
    
    transformer:
      raw:
        - name: Standardize
        # - name: RandomFlip
        # - name: RandomRotate90
        # - name: RandomRotate
        #   # rotate only in ZY plane due to anisotropy
        #   axes: [[2, 1]]
        #   angle_spectrum: 45
        #   mode: reflect
        # - name: ElasticDeformation
        #   spline_order: 3
        # - name: GaussianBlur3D
        #   execution_probability: 0.5
        # - name: AdditiveGaussianNoise
        #   execution_probability: 0.2
        # - name: AdditivePoissonNoise
        #   execution_probability: 0.2
        - name: ToTensor
          expand_dims: true
      label:
        # - name: RandomFlip
        # - name: RandomRotate90
        # - name: RandomRotate
        #   # rotate only in ZY plane due to anisotropy
        #   axes: [[2, 1]]
        #   angle_spectrum: 45
        #   mode: reflect
        # - name: ElasticDeformation
        #   spline_order: 0
        - name: BlobsToMask
          append_label: false
          boundary: false
        - name: ToTensor
          expand_dims: false

  # configuration of the val loader
  val:
    # path to the val datasets
    file_paths:
      - /media/wlsdzyzl/DATA1/datasets/ASOCA/nii/cropped_middle/fold1
    mask_path: /home/wlsdzyzl/project/pyramid-3dunet/generated_files/mask/3d_asoca/fold1/val
    # SliceBuilder configuration, i.e. how to iterate over the input volume patch-by-patch
    slice_builder:
      name: MaskedSliceBuilder
      # val patch size given to the network (adapt to fit in your GPU mem, generally the bigger patch the better)
      patch_shape: [32, 32, 32]
      # stride between patches
      stride_shape: [24, 24, 24]
      # minimum volume of the labels in the patch
      threshold: 0
      # probability of accepting patches which do not fulfil the threshold criterion
      slack_acceptance: 0.01

    # data augmentation
    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: BlobsToMask
          append_label: false
          boundary: false
        - name: ToTensor
          expand_dims: false

